name: Doxygen CI

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install requirements
        run: |
          brew install graphviz ninja doxygen
      - name: configure
        run: cmake -G Ninja -B ./build -S .
      - name: build
        run: cmake --build build -t docs
      - name: gh-pages
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          clean: false
