name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install requirements
        run: |
          sudo apt install graphviz doxygen
      - name: github_pages
        uses: actions/checkout@v4
        with:
          ref: "github_pages"
          clean: false
