name: Doxygen CI

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install requirements
        run: |
          brew install graphviz ninja doxygen
      - name: build
        run: cmake --build build -t doc
      - name: Doxygen Action              
        uses: mattnotmitt/doxygen-action@1.9.5
